name: Check Release Branch for Main Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch name
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          echo "Source branch: $SOURCE_BRANCH"
          if [[ "$SOURCE_BRANCH" != release/* ]]; then
            echo "::error::Pull Request from branch '$SOURCE_BRANCH' cannot be merged into 'main'. Only branches starting with 'release/' are allowed."
            exit 1
          else
            echo "Source branch '$SOURCE_BRANCH' is a valid release branch."
          fi