name: CI/CD Pipeline com Tagging

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # -----------------------------------------------------------------
  # JOB 1: Testa, Linta, Constroi e Faz Upload do Artefato
  # -----------------------------------------------------------------
  test-and-build:
    name: Test, Lint & Build
    # ... (este job está correto, sem mudanças) ...
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Você pode remover se definir "packageManager" no package.json

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test:ci
      
      - name: Build project
        run: pnpm run build
      
      # --- PASSO CRÍTICO ADICIONADO ---
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/ # <-- O nome da pasta que seu build cria

  # -----------------------------------------------------------------
  # JOB 2: Deploy para Produção (Vercel)
  # -----------------------------------------------------------------
  deploy-production:
    name: Deploy to Production
    needs: test-and-build # Depende do job de teste e build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      # --- PASSO DA CORREÇÃO ADICIONADO ---
      # A Vercel Action precisa do .git para ler o commit
      - name: Checkout code
        uses: actions/checkout@v4

      # --- PASSO CRÍTICO ADICIONADO ---
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build # <-- Baixa os arquivos para uma pasta 'build'

      # Lista os arquivos (para debug, pode remover depois)
      - name: List files
        run: ls -lR

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "build/ --prod" # <-- Publica a pasta 'build/'

  # -----------------------------------------------------------------
  # JOB 3: Deploy de Preview
  # -----------------------------------------------------------------
  deploy-preview:
    name: Deploy Preview
    needs: test-and-build # Depende do job de teste e build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/develop' && github.event_name == 'push')

    steps:
      # --- PASSO DA CORREÇÃO ADICIONADO ---
      # A Vercel Action precisa do .git para ler o commit
      - name: Checkout code
        uses: actions/checkout@v4

      # --- PASSO CRÍTICO ADICIONADO ---
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build # <-- Baixa os arquivos para uma pasta 'build'
      
      # Lista os arquivos (para debug, pode remover depois)
      - name: List files
        run: ls -lR

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "build/" # <-- Publica a pasta 'build/'

  # -----------------------------------------------------------------
  # JOB 4: Criar Tag de Versão (Mantido como estava)
  # -----------------------------------------------------------------
  tag-release:
    name: Tag Release
    needs: deploy-production # <-- Roda APÓS o deploy de produção
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG_VERSION}"; then
            echo "Tag $TAG_VERSION already exists. Skipping..."
            echo "SKIP_TAG=true" >> $GITHUB_ENV
          else
            echo "Tag $TAG_VERSION does not exist. Proceeding..."
            echo "SKIP_TAG=false" >> $GITHUB_ENV
          fi
      
      - name: Create and Push Tag
        if: env.SKIP_TAG == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_VERSION -m "Release $TAG_VERSION"
          git push origin $TAG_VERSION

